version: 0.2

env:
  variables:
    REGIONS: "us-east-1 ap-south-1"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing AWS CLI if missing...
      - pip install --upgrade awscli

  build:
    commands:
      - echo "Deploying to regions: $REGIONS"
      - |
        for REGION in $REGIONS; do
          echo "------------------------------"
          echo "Deploying Network Stack to $REGION"
          echo "------------------------------"
          aws cloudformation deploy \
            --template-file infra/vpc_stack.yaml \
            --stack-name vpc-stack-$REGION \
            --capabilities CAPABILITY_NAMED_IAM \
            --region $REGION

          echo "Deploying ALB + WAF Stack to $REGION"
          aws cloudformation deploy \
            --template-file infra/alb_stack.yaml \
            --stack-name alb-stack-$REGION \
            --capabilities CAPABILITY_NAMED_IAM \
            --region $REGION

          echo "Deploying ECS Stack to $REGION"
          aws cloudformation deploy \
            --template-file infra/ecs_stack.yaml \
            --stack-name ecs-stack-$REGION \
            --capabilities CAPABILITY_NAMED_IAM \
            --region $REGION

          # Optional: deploy CloudFront only once in us-east-1
          if [ "$REGION" = "us-east-1" ]; then
            echo "Deploying CloudFront Stack in $REGION"
            aws cloudformation deploy \
              --template-file infra/waf_cloudfront_stack.yaml \
              --stack-name waf-cloudfront-stack \
              --capabilities CAPABILITY_NAMED_IAM \
              --region $REGION
          fi
        done
