version: 0.2

phases:
  build:
    commands:
      - echo "Starting multi-region deployment..."
      - REGIONS="us-east-1 ap-southeast-1"
      - for REGION in $REGIONS; do
          echo "Deploying to region: $REGION";

          # VPC Stack
          if ! aws cloudformation describe-stacks --region $REGION --stack-name CMS3-VPC-Stack-$REGION >/dev/null 2>&1; then
            aws cloudformation deploy \
              --template-file vpc_template.yaml \
              --stack-name CMS3-VPC-Stack-$REGION \
              --region $REGION \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides RegionName=$REGION;
          else
            echo "VPC stack already exists in $REGION, skipping...";
          fi

          # ALB Stack
          if ! aws cloudformation describe-stacks --region $REGION --stack-name CMS3-ALB-Stack-$REGION >/dev/null 2>&1; then
            aws cloudformation deploy \
              --template-file alb_stack.yaml \
              --stack-name CMS3-ALB-Stack-$REGION \
              --region $REGION \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides RegionName=$REGION;
          else
            echo "ALB stack already exists in $REGION, skipping...";
          fi

          # ECS Stack
          if ! aws cloudformation describe-stacks --region $REGION --stack-name CMS3-ECS-EC2-Stack-$REGION >/dev/null 2>&1; then
            aws cloudformation deploy \
              --template-file ecs_stack.yaml \
              --stack-name CMS3-ECS-EC2-Stack-$REGION \
              --region $REGION \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides RegionName=$REGION KeyName=my-key-name;
          else
            echo "ECS stack already exists in $REGION, skipping...";
          fi

        done
