#ALB Template
---
AWSTemplateFormatVersion: "2010-09-09"
Description: ALB, Security Group, Target Groups, Listeners (HTTPS, Node.js), using existing VPC and subnets

Parameters:
  ACMCertificateArn:
    Description: ACM certificate ARN for HTTPS listener
    Type: String

Resources:
  CMS3ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP and HTTPS traffic
      VpcId: !ImportValue CMS3-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: CMS3ALBSecurityGroup

  CMS3HTTPTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue CMS3-VPC-ID
      Protocol: HTTP
      Port: 80
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: CMS3HTTPTargetGroup

  CMS3HTTPSTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue CMS3-VPC-ID
      Protocol: HTTPS
      Port: 443
      TargetType: ip
      HealthCheckProtocol: HTTPS
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: CMS3HTTPSTargetGroup

  CMSNodejsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue CMS3-VPC-ID
      Protocol: HTTP
      Port: 8080
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: CMSNodejsTargetGroup

  CMS3ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: CMS3ApplicationLoadBalancer
      Scheme: internet-facing
      Type: application
      Subnets:
        - !ImportValue CMS3-PublicSubnet-1
        - !ImportValue CMS3-PublicSubnet-2
      SecurityGroups:
        - !Ref CMS3ALBSecurityGroup
      Tags:
        - Key: Name
          Value: CMS3ALB

  CMS3ALBHTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref CMS3ApplicationLoadBalancer
      Protocol: HTTPS
      Port: 443
      Certificates:
        - CertificateArn: !Ref ACMCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref CMS3HTTPSTargetGroup

  CMS3NodejsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref CMS3ApplicationLoadBalancer
      Protocol: HTTP
      Port: 8080
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref CMSNodejsTargetGroup

Outputs:
  ALBArn:
    Description: Application Load Balancer ARN
    Value: !Ref CMS3ApplicationLoadBalancer
    Export:
      Name: CMS3-ALB-ARN

  ALBHTTPSListenerArn:
    Description: HTTPS Listener ARN
    Value: !Ref CMS3ALBHTTPSListener
    Export:
      Name: CMS3-ALB-HTTPS-Listener

  ALBSecurityGroupId:
    Description: ALB Security Group ID
    Value: !Ref CMS3ALBSecurityGroup
    Export:
      Name: CMS3-ALB-SG-ID

  NodejsTargetGroupArn:
    Description: Node.js Target Group ARN
    Value: !Ref CMSNodejsTargetGroup
    Export:
      Name: CMS3-TG-Nodejs

  HTTPTargetGroupArn:
    Description: HTTP Target Group ARN
    Value: !Ref CMS3HTTPTargetGroup
    Export:
      Name: CMS3-TG-HTTP

  HTTPSTargetGroupArn:
    Description: HTTPS Target Group ARN
    Value: !Ref CMS3HTTPSTargetGroup
    Export:
      Name: CMS3-TG-HTTPS
