AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for WAF and CloudFront with two ALBs as origins

Resources:
  CMS3CloudFrontWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: CMS3CloudFrontWebACL
      Scope: CLOUDFRONT
      Description: WAF WebACL for CMS3 CloudFront Distribution
      DefaultAction: 
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: CMSWebACLMetric
      Rules:
        - Name: AWS-AmazonIPReputationList
          Priority: 0
          OverrideAction: { None: {} }
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AmazonIPReputationList
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList

        - Name: AWS-CommonRuleSet
          Priority: 1
          OverrideAction: { None: {} }
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWS-CommonRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet

        - Name: AWS-KnownBadInputsRuleSet
          Priority: 2
          OverrideAction: { None: {} }
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWS-KnownBadInputsRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet

  CMS3CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: ALBOriginUSEast1
            DomainName:
              !ImportValue CMS3-ALB-DNS-us-east-1
            CustomOriginConfig:
              HTTPPort: 8080
              HTTPSPort: 443
              OriginProtocolPolicy: http-only

          - Id: ALBOriginAPSoutheast1
            DomainName:
              !ImportValue CMS3-ALB-DNS-ap-southeast-1
            CustomOriginConfig:
              HTTPPort: 8080
              HTTPSPort: 443
              OriginProtocolPolicy: http-only

        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: ALBOriginUSEast1
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

        CacheBehaviors:
          - PathPattern: "/apac/*"
            TargetOriginId: ALBOriginAPSoutheast1
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none

        WebACLId: !GetAtt CMS3CloudFrontWebACL.Arn

        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:722136401996:certificate/44fa3ab7-f45f-493c-9be0-20936f308f26
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        PriceClass: PriceClass_100
